[package]
name = "vm"
version = "0.1.0"
edition = "2024"

[dependencies]
configuration = { path = "../configuration" }

elf = "0.8.0"
riscv-isa = "0.3.1"
test-log = { version = "0.2.18", features = ["trace"] }
thiserror = "2.0.12"
tracing = "0.1.41"
