[package]
name = "vm"
version = "0.1.0"
edition = "2024"

[dependencies]
configuration = { workspace = true }

elf = { workspace = true }
riscv-isa = { workspace = true }
test-log = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
