[tools]

[tasks.debug]
run = "RUST_LOG=debug cargo run --bin zkvm --features debug,parallel --release"

[tasks.fix_vars_bench]
run = "cargo bench -p stark-rings-poly --bench fix_variables"

[tasks.test]
run = "cargo test --workspace -j 8"

[tasks.perf]
usage = '''
arg "<name>" help="perf record output name (without extension)"
'''
run = [
	'cargo build --bin zkvm --features debug,latticefold/parallel --release',
	'taskset -c 0-7 perf record -F 99 --call-graph dwarf -o "benches/${usage_name?}.data" -- env RUST_LOG=info ./target/release/zkvm'
]
