[tools]

[tasks.debug]
run = "RUST_LOG=debug cargo run --bin zkvm --features debug,latticefold/parallel --release -- --guest ./target/riscv32imac-unknown-none-elf/release/fibonacci"

[tasks.copy-to-vm]
run = [
	'cargo build --bin zkvm --features latticefold/parallel --release',
	'rsync -avzP ./target/release/zkvm dp:/home/ubuntu/latticeum/',
	'rsync -avzP ./target/riscv32imac-unknown-none-elf/release/fibonacci dp:/home/ubuntu/latticeum/'
]

[tasks.test]
run = "cargo test --workspace -j 8"

[tasks.perf]
usage = '''
arg "<name>" help="perf record output name (without extension)"
'''
run = [
	'cargo build --bin zkvm --features debug,latticefold/parallel --release',
	'taskset -c 0-7 perf record -F 99 --call-graph dwarf -o "benches/${usage_name?}.data" -- env RUST_LOG=info ./target/release/zkvm'
]
